meuprojeto/meuprojeto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pecas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

meuprojeto/pecas/urls.py
from django.urls import path
from .views import (
    ProdutoListView, ProdutoDetailView, ProdutoCreateView, ProdutoUpdateView,
    ProdutoDeleteView, CriarContaView,remover_do_carrinho ,KitUpgradeListView,carrinho,AddNoCarrinho ,LoginView, pcgamer,hardwares,notebook,monitor,
    promocao,atendimento,remover_do_carrinho,gerenciar_produtos,DadosUsuarioView,EditarEmailView
)
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', ProdutoListView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'), 
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),

    path('produto/<int:pk>/', ProdutoDetailView.as_view(), name='produto-detail'),
    path('produto/novo/', ProdutoCreateView.as_view(), name='produto-create'),
    path('produto/<int:pk>/editar/', ProdutoUpdateView.as_view(), name='produto-update'),
    path('produto/<int:pk>/deletar/', ProdutoDeleteView.as_view(), name='produto-delete'),

    path('criar-conta/', CriarContaView.as_view(), name='criar-conta'),
    path('kitupgrade/', KitUpgradeListView.as_view(), name='kitupgrade'),
    path('pc-gamer/', pcgamer.as_view(), name='pc_gamer'),
    path('hardwares/', hardwares.as_view(), name='hardwares'),
    path('monitor/', monitor.as_view(), name='monitor'),
    path('promocao/', promocao.as_view(), name='promocao'),
    path('atendimento/', atendimento.as_view(), name='atendimento'),
    path('notebook/', notebook.as_view(), name='notebook'),
    path('add-no-carrinho/<int:pk>/', AddNoCarrinho.as_view(), name='add_no_carrinho'),
    path('carrinho/', carrinho.as_view(), name='carrinho'),
    path('remover-do-carrinho/<int:pk>/', remover_do_carrinho.as_view(), name='remover'),
    path('gerenciar-produtos/', gerenciar_produtos.as_view(), name='gerenciar_produtos'),
    path('dados-usuario/', DadosUsuarioView.as_view(), name='dados_usuario'),
    path('editar-email/', EditarEmailView.as_view(), name='editar_email'),


    
]

meuprojeto/pecas/models.py
from django.db import models
from django.contrib.auth.models import User

        
class Categoria(models.Model):
    nome = models.CharField(max_length=100)
    def __str__(self):
        return self.nome


class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=11, unique=True)
    genero = models.CharField(max_length=20)
    data_nascimento = models.DateField()
    telefone = models.CharField(max_length=15)
    is_vendedor = models.BooleanField(default=False) 

    def __str__(self):
        return self.user.get_full_name() or self.user.username


class Produto(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    imagem = models.ImageField(upload_to='produtos/')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='produtos')
    data_cadastro = models.DateTimeField(auto_now_add=True)
    


    def __str__(self):
        return self.nome
    

    
class Review(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, related_name='reviews')
    autor = models.CharField(max_length=100)
    titulo = models.CharField(max_length=200)
    conteudo = models.TextField()
    nota = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.titulo} - {self.produto.nome}"

class Comentario(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.CharField(max_length=100)
    texto = models.TextField()
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentário de {self.autor}"

meuprojeto/pecas/forms.py
from django import forms
from django.contrib.auth.models import User

class EmailUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

meuprojeto/pecas/views.py
from urllib import request
from .models import Produto,Perfil
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect,get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from .forms import EmailUpdateForm
from django.views.generic import TemplateView




class CriarContaView(View):
    def get(self, request):
        return render(request, 'pecas/crud/cadastro.html')

    def post(self, request):
        nome = request.POST.get('nome')
        cpf = request.POST.get('cpf', '').replace('.', '').replace('-', '').strip()
        genero = request.POST.get('genero')
        data = request.POST.get('data')
        telefone = request.POST.get('telefone')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        confirmar = request.POST.get('confirmar')
        vendedor = request.POST.get('origem')



        if Perfil.objects.filter(cpf=cpf).exists():
            return render(request, 'pecas/crud/cadastro.html', {
                'erro': 'CPF já cadastrado.'
            })
        
        if vendedor not in ["sim", "nao"]:
            return render(request, 'pecas/crud/cadastro.html', {
                'erro': 'Seleção inválida para vendedor.'
            })
        

        if len(cpf) != 11 or not cpf.isdigit():
            return render(request, 'pecas/crud/cadastro.html', {
                'erro': 'CPF inválido. Deve conter 11 dígitos numéricos.'
            })


        if senha != confirmar:
            return render(request, 'pecas/crud/cadastro.html', {
                'erro': 'As senhas não coincidem.'
            })

        if User.objects.filter(username=email).exists():
            return render(request, 'pecas/crud/cadastro.html', {
                'erro': 'Este e-mail já está em uso.'
            })
        

        user = User.objects.create_user(username=email, email=email, password=senha)
        user.first_name = nome

        is_vendedor = False
        if vendedor == "Sim":
            is_vendedor = True 
            user.is_active = True
            user.is_staff = True
            user.is_superuser = True
        
        user.save()

        Perfil.objects.create(
            user=user,
            cpf=cpf,
            genero=genero,
            data_nascimento=data,
            telefone=telefone,
            is_vendedor=is_vendedor
        )
        return redirect('home')




class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('dados_usuario')
        return render(request, 'pecas/crud/login.html')

    def post(self, request):

        email = request.POST.get('email')
        senha = request.POST.get('senha')

        user = authenticate(request, username=email, password=senha)

        if user is not None:
            login(request, user)
            return redirect('dados_usuario')
        else:
            return render(request, 'pecas/crud/login.html', {
                'erro': 'Email ou senha inválidos.',
            })



class EditarEmailView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'pecas/editar_dados.html')

    def post(self, request):
        email = request.POST.get('email') 
        if User.objects.filter(email=email).exclude(id=request.user.id).exists():
            return render(request, 'pecas/editar_dados.html', {
                'erro': 'Este e-mail já está em uso por outro usuário.'
            })
        request.user.email = email
        request.user.username = email
        request.user.save()
        return redirect('dados_usuario')


class DadosUsuarioView(LoginRequiredMixin, View):
    def get(self, request):
        perfil = request.user.perfil
        return render(request, 'pecas/dados.html', {'perfil': perfil})







class AddNoCarrinho(View):
    def post(self, request, pk):
        if not request.user.is_authenticated:
            return redirect('login')

        produto = get_object_or_404(Produto, pk=pk)
    
        carrinho = request.session.get('carrinho', [])
        carrinho.append(produto.id)
        request.session['carrinho'] = carrinho
        return redirect('carrinho')

class remover_do_carrinho(View):
    def post(self, request, pk):
        if not request.user.is_authenticated:
            return redirect('login')

        produto = get_object_or_404(Produto, pk=pk)
    
        carrinho = request.session.get('carrinho', [])
        if produto.id in carrinho:
            carrinho.remove(produto.id)
            request.session['carrinho'] = carrinho
        return redirect('carrinho')

class ProdutoListView(ListView):
    model = Produto
    template_name = 'pecas/index.html'
    context_object_name = 'produtos'
    paginate_by = 6

    def get_queryset(self, *args, **kwargs):
        queryset = Produto.objects.all()
        ordenar = self.request.GET.get('ordenar_por')
        pesquisar = self.request.GET.get('q')

        if pesquisar:
            queryset = queryset.filter(nome__icontains=pesquisar)  
        if ordenar:
            queryset = queryset.order_by(ordenar)
        return queryset


class painel_vendedor(LoginRequiredMixin, View):
    def get(self, request):
        if not hasattr(request.user, 'perfil') or not request.user.perfil.is_vendedor:
            return redirect('home')  

        return render(request, 'pecas/painel_vendedor.html')


class ProdutoDetailView(DetailView):
    model = Produto
    template_name = 'pecas/protudos/produto_detail.html'
    context_object_name = 'produto_detalhe'





class KitUpgradeListView(ListView):
    model = Produto
    queryset = Produto.objects.filter(categoria__nome='Kit Upgrade')
    paginate_by = 6
    template_name = 'pecas/protudos/kitupgrade.html'
    context_object_name = 'kits'

class monitor(ListView):
    model = Produto
    queryset = Produto.objects.filter(categoria__nome='Monitor')
    paginate_by = 6
    template_name = 'pecas/protudos/monitor.html'
    context_object_name = 'monitores'

class promocao(ListView):
    model = Produto
    queryset = Produto.objects.filter(categoria__nome='Monitor')
    paginate_by = 6
    template_name = 'pecas/protudos/promocao.html'
    context_object_name = 'produtos_promocao'

class atendimento(ListView):
    model = Produto
    template_name = 'pecas/protudos/atendimento.html'
    context_object_name = 'atendimento'
    
class notebook(ListView):
    model = Produto
    queryset = Produto.objects.filter(categoria__nome='Notebook')
    paginate_by = 6
    template_name = 'pecas/protudos/notebook.html'
    context_object_name = 'notebooks'
    

class pcgamer(ListView):
    model = Produto
    queryset = Produto.objects.filter(categoria__nome='PC Gamer')
    paginate_by = 6
    template_name = 'pecas/protudos/pcgamer.html'
    context_object_name = 'pcs'

class hardwares(ListView):
    model = Produto
    queryset = Produto.objects.filter(categoria__nome='Hardware')
    paginate_by = 6
    template_name = 'pecas/protudos/hardware.html'
    context_object_name = 'hardwares'

class carrinho(ListView):
    model = Produto
    template_name = 'pecas/protudos/carrinho.html'
    context_object_name = 'produtos'

    def get_queryset(self):
        carrinho_ids = self.request.session.get('carrinho', [])
        return Produto.objects.filter(id__in=carrinho_ids)



class ProdutoCreateView(LoginRequiredMixin, CreateView):
    model = Produto
    fields = ['nome', 'descricao', 'preco', 'imagem', 'categoria']
    template_name = 'pecas/criar.html'
    success_url = reverse_lazy('gerenciar_produtos')  

class gerenciar_produtos(LoginRequiredMixin, ListView):
    model = Produto
    template_name = 'pecas/gerenciar.html'
    context_object_name = 'produtos'


class ProdutoUpdateView(LoginRequiredMixin, UpdateView):
    model = Produto
    fields = ['nome', 'descricao', 'preco', 'imagem', 'categoria']
    template_name = 'pecas/editar.html'
    success_url = reverse_lazy('gerenciar_produtos')  


class ProdutoDeleteView(LoginRequiredMixin, DeleteView):
    model = Produto
    template_name = 'pecas/deletar.html'
    success_url = reverse_lazy('gerenciar_produtos')  

meuprojeto/pecas/templates/pecas/crud/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GnomosGames</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'pecas/style.css' %}">
</head>
<body class="cadastro-page">
    <!-- Navbar Principal -->
<nav class="navbar navbar-expand-lg navbar-custom py-2 ">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold text-danger" href="{% url 'home' %}">
      <i class="fas fa-store"></i> GnomosGames
    </a>

    <form class="d-flex mx-auto" role="search">
      <input class="form-control me-2" type="search" placeholder="Pesquisar produtos" aria-label="Search">
      <button class="btn btn-danger" type="submit"><i class="fas fa-search"></i></button>
    </form>

    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class="nav-link text-danger" href="{% url 'login' %}"><i class="fas fa-user"></i> Conta</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-danger" href="{% url 'carrinho' %}"><i class="fas fa-shopping-cart"></i> Carrinho</a>
      </li>
    </ul>>
  </div>
</nav>

<!-- Submenu -->
<div class="submenu-bar d-flex flex-wrap align-items-center">
    <a href="{% url 'promocao' %}">Promoções</a>
    <a href="{% url 'pc_gamer' %}">Pc Gamer</a>
    <a href="{% url 'kitupgrade' %}">Kit Upgrade</a>
    <a href="{% url 'hardwares' %}">Hardware</a>
    <a href="{% url 'notebook' %}">Notebook</a>
    <a href="{% url 'monitor' %}">Monitores</a>
    <a href="{% url 'atendimento' %}">Atendimento</a>
    </div>
<div class="container-form">
  <h2 class="title">CRIAR CONTA</h2>
  <form method="post" action="{% url 'criar-conta' %}">
  {% csrf_token %}
  
  <div class="row mb-3">
    <div class="col-md-6">
      <label for="nome" class="form-label">Nome completo*</label>
      <input type="text" class="form-control" id="nome" name="nome" required>
    </div>
    <div class="col-md-6">
      <label for="cpf" class="form-label">CPF*</label>
      <input type="text" class="form-control" id="cpf" name="cpf" required>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-6">
      <label for="genero" class="form-label">Gênero**</label>
      <select class="form-select" id="genero" name="genero" required>
        <option value="">Selecione</option>
        <option value="homem">Homem</option>
        <option value="mulher">Mulher</option>
        <option value="outros">Outros</option>
        <option value="nao">Não especificar</option>
      </select>
    </div>
    <div class="col-md-6">
      <label for="data" class="form-label">Data de nascimento*</label>
      <input type="date" class="form-control" id="data" name="data" required>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-6">
      <label for="telefone" class="form-label">Telefone celular*</label>
      <input type="tel" class="form-control" id="telefone" name="telefone" required>
    </div>
    <div class="col-md-6">
      <label for="email" class="form-label">E-mail*</label>
      <input type="email" class="form-control" id="email" name="email" required>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-6">
      <label for="senha" class="form-label">Crie sua senha*</label>
      <input type="password" class="form-control" id="senha" name="senha" required>
    </div>
    <div class="col-md-6">
      <label for="confirmar" class="form-label">Confirme sua senha*</label>
      <input type="password" class="form-control" id="confirmar" name="confirmar" required>
    </div>
  </div>

  <div class="mb-3">
    <label for="origem" class="form-label">Quer Ser vendedor?</label>
    <select class="form-select" id="origem" name="origem" required>
      <option value="">Selecione</option>
      <option value="sim">Sim</option>
      <option value="nao">Nao</option>
    
    </select>
  </div>

  <div class="form-check mb-2">
    <input class="form-check-input" type="checkbox" id="ofertas" name="ofertas">
    <label class="form-check-label" for="ofertas">
      Quero receber ofertas por e-mail, SMS ou WhatsApp
    </label>
  </div>

  <div class="form-check mb-4">
    <input class="form-check-input" type="checkbox" id="termos" name="termos" required>
    <label class="form-check-label" for="termos">
      Li e concordo com os <a href="#" class="text-decoration-none text-danger">termos e políticas de privacidade*</a>
    </label>
  </div>

  <div class="text-center">
    <button type="submit" class="btn btn-orange">CONTINUAR</button>
  </div>

  <div class="form-footer mt-4">
    (** As opções “homem” e “mulher” abrangem cisgêneros e transgêneros. A opção “outros” inclui gênero fluido, não-binário, queer, etc. Use “não especificar” se preferir não responder.)
  </div>
  
    {% if erro %}
<div class="alert alert-danger text-center" role="alert">
  {{ erro }}
</div>
  {% endif %}

</form>

</div>
<!-- Seções de links -->
<footer class="recomendacoes text-light pt-5 pb-4">
  <div class="container">
    <div class="row text-start">
      <!-- Coluna 1 -->
      <div class="col-md-3 mb-4">
        <h6 class="fw-bold">Conheça-nos</h6>
        <ul class="list-unstyled">
          <li><a href="#" class="text-light text-decoration-none">Sobre a ShopOnline</a></li>  
          <li><a href="#" class="text-light text-decoration-none">Comunidade</a></li> 
        </ul>
      </div>

      <!-- Coluna 2 -->
      <div class="col-md-3 mb-4">
        <h6 class="fw-bold">Ganhe dinheiro conosco</h6>
        <ul class="list-unstyled">
          <li><a href="#" class="text-light text-decoration-none">Venda na ShopOnline</a></li>
          <li><a href="#" class="text-light text-decoration-none">Anuncie seus produtos</a></li>
        </ul>
      </div>

      <!-- Coluna 3 -->
      <div class="col-md-3 mb-4">
        <h6 class="fw-bold">Pagamento</h6>
        <ul class="list-unstyled">
          <li><a href="#" class="text-light text-decoration-none">Meios de Pagamento</a></li>
          <li><a href="#" class="text-light text-decoration-none">Cartão de Crédito</a></li>
        </ul>
      </div>

      <!-- Coluna 4 -->
      <div class="col-md-3 mb-4">
        <h6 class="fw-bold">Deixe-nos ajudar você</h6>
        <ul class="list-unstyled">
          <li><a href="#" class="text-light text-decoration-none">Sua conta</a></li>
          <li><a href="#" class="text-light text-decoration-none">Frete e prazo de entrega</a></li>
          <li><a href="#" class="text-light text-decoration-none">Ajuda</a></li>
        </ul>
      </div>
    </div>
  </div>
  {% if form.errors %}
  <ul>
    {% for field in form %}
      {% for error in field.errors %}
        <li><strong>{{ field.label }}:</strong> {{ error }}</li>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <li>{{ error }}</li>
    {% endfor %}
  </ul>
{% endif %}

  <!-- Linha inferior -->


  <div class="text-center mt-3 small text-secondary">
    <a href="#" class="text-decoration-none text-secondary">Condições de Uso</a> |
    <a href="#" class="text-decoration-none text-secondary">Privacidade</a> |
    <a href="#" class="text-decoration-none text-secondary">Cookies</a> |
    <a href="#" class="text-decoration-none text-secondary">Anúncios baseados em interesses</a>
    <br>
    © 2021-2025 ShopOnline, Inc. ou suas afiliadas
  </div>
</footer>



</body>
</html>

meuprojeto/pecas/templates/pecas/crud/criar.html
{% extends 'base.html' %}

{% block title %}
    Criar Produto
{% endblock %}

{% block content %}
<h2 class="fw-bold text-center mb-4">Criar Produto</h2>

<form method="post" enctype="multipart/form-data" class="mx-auto" style="max-width: 600px;">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="mb-3">
        <label for="id_nome" class="form-label">Nome</label>
        {{ form.nome.errors }}
        {{ form.nome }}

    </div>

    <div class="mb-3">
        <label for="id_descricao" class="form-label">Descrição</label>
        {{ form.descricao.errors }}
        {{ form.descricao}}
    </div>

    <div class="mb-3">
        <label for="id_preco" class="form-label">Preço</label>
        {{ form.preco.errors }}
        {{ form.preco}}
    </div>

    <div class="mb-3">
        <label for="id_imagem" class="form-label">Imagem</label>
        {{ form.imagem.errors }}
        {{ form.imagem }}
    </div>

    <div class="mb-3">
        <label for="id_categoria" class="form-label">Categoria</label>
        {{ form.categoria.errors }}
        {{ form.categoria}}
    </div>

    <button type="submit" class="btn btn-primary">Criar Produto</button>
    <a href="{% url 'home' %}" class="btn btn-secondary ms-2">Cancelar</a>
</form>
{% endblock %}

meuprojeto/pecas/templates/pecas/crud/deletar.html
{% extends 'base.html' %}
{% block title %}Excluir Produto{% endblock %}

{% block content %}
<h2 class="fw-bold text-center mb-4">Excluir Produto</h2>

<div class="text-center mb-4">
    {% if object.imagem %}
        <img src="{{ object.imagem.url }}" alt="{{ object.nome }}" class="img-thumbnail" style="max-width: 300px;">
    {% endif %}
</div>

<div class="alert alert-warning text-center" role="alert">
    Tem certeza que deseja excluir o produto <strong>{{ object.nome }}</strong>?
</div>

<form method="post" class="text-center">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Sim, excluir</button>
    <a href="{% url 'home' %}" class="btn btn-secondary ms-2">Cancelar</a>
</form>
{% endblock %}

meuprojeto/pecas/templates/pecas/crud/editar.html
{% extends 'base.html' %}

{% block title %}
    Editar Produto
{% endblock %}

{% block content %}
<h2 class="fw-bold text-center mb-4">Editar Produto</h2>

<form method="post" enctype="multipart/form-data" class="mx-auto" style="max-width: 600px;">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="mb-3">
        <label for="id_nome" class="form-label">Nome</label>
        {{ form.nome.errors }}
        {{ form.nome }}
    </div>

    <div class="mb-3">
        <label for="id_descricao" class="form-label">Descrição</label>
        {{ form.descricao.errors }}
        {{ form.descricao }}
    </div>

    <div class="mb-3">
        <label for="id_preco" class="form-label">Preço</label>
        {{ form.preco.errors }}
        {{ form.preco }}
    </div>

    <div class="mb-3">
        <label for="id_imagem" class="form-label">Imagem</label>
        {{ form.imagem.errors }}
        {{ form.imagem }}
        {% if form.instance.imagem %}
            <img src="{{ form.instance.imagem.url }}" alt="Imagem atual" class="img-thumbnail mt-2" style="max-width: 200px;">
        {% endif %}
    </div>

    <div class="mb-3">
        <label for="id_categoria" class="form-label">Categoria</label>
        {{ form.categoria.errors }}
        {{ form.categoria }}
    </div>

    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
    <a href="{% url 'home' %}" class="btn btn-secondary ms-2">Cancelar</a>
</form>
{% endblock %}